/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./components/atoms/AppIcon.vue')['default']
    ErrorBanner: typeof import('./components/molecules/ErrorBanner.vue')['default']
    FeatureHighlight: typeof import('./components/molecules/landing-page/FeatureHighlight.vue')['default']
    Footer: typeof import('./components/app-shell/footer/Footer.vue')['default']
    FooterBranding: typeof import('./components/app-shell/footer/FooterBranding.vue')['default']
    FooterCredits: typeof import('./components/app-shell/footer/FooterCredits.vue')['default']
    FooterLinks: typeof import('./components/app-shell/footer/FooterLinks.vue')['default']
    FooterSocials: typeof import('./components/app-shell/footer/FooterSocials.vue')['default']
    ForgotPasswordForm: typeof import('./components/organisms/forgot-password/ForgotPasswordForm.vue')['default']
    InputField: typeof import('./components/atoms/InputField.vue')['default']
    LandingExperienceCarousel: typeof import('./components/organisms/landing-page/LandingExperienceCarousel.vue')['default']
    LandingHeroSection: typeof import('./components/organisms/landing-page/LandingHeroSection.vue')['default']
    LandingValueShowcase: typeof import('./components/organisms/landing-page/LandingValueShowcase.vue')['default']
    LoadingSpinner: typeof import('./components/atoms/LoadingSpinner.vue')['default']
    LoginForm: typeof import('./components/organisms/login-form/LoginForm.vue')['default']
    MainLayout: typeof import('./components/layouts/MainLayout.vue')['default']
    Navbar: typeof import('./components/app-shell/navbar/Navbar.vue')['default']
    NavbarDesktop: typeof import('./components/app-shell/navbar/NavbarDesktop.vue')['default']
    NavbarMobile: typeof import('./components/app-shell/navbar/NavbarMobile.vue')['default']
    PlayablePreviewCarousel: typeof import('./components/organisms/landing-page/PlayablePreviewCarousel.vue')['default']
    ProfileDropdown: typeof import('./components/app-shell/navbar/ProfileDropdown.vue')['default']
    RegisterForm: typeof import('./components/organisms/register-form/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreeColumnShell: typeof import('./components/layouts/ThreeColumnShell.vue')['default']
    Toast: typeof import('./components/molecules/Toast.vue')['default']
    WhyChooseUsCard: typeof import('./components/molecules/landing-page/WhyChooseUsCard.vue')['default']
    WidgetWrapper: typeof import('./components/molecules/WidgetWrapper.vue')['default']
  }
}
