/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./components/atoms/AppIcon.vue')['default']
    ErrorBanner: typeof import('./components/molecules/ErrorBanner.vue')['default']
    Footer: typeof import('./components/app-shell/footer/Footer.vue')['default']
    FooterBranding: typeof import('./components/app-shell/footer/FooterBranding.vue')['default']
    FooterCredits: typeof import('./components/app-shell/footer/FooterCredits.vue')['default']
    FooterLinks: typeof import('./components/app-shell/footer/FooterLinks.vue')['default']
    FooterSocials: typeof import('./components/app-shell/footer/FooterSocials.vue')['default']
    InputField: typeof import('./components/atoms/InputField.vue')['default']
    LoadingSpinner: typeof import('./components/atoms/LoadingSpinner.vue')['default']
    MainLayout: typeof import('./components/layouts/MainLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreeColumnShell: typeof import('./components/layouts/ThreeColumnShell.vue')['default']
    Toast: typeof import('./components/molecules/Toast.vue')['default']
    WidgetWrapper: typeof import('./components/molecules/WidgetWrapper.vue')['default']
  }
}
